plugins:
  mozillians_enabled:
    default: false
    client: true
  mozillians_enable_ssl:
    default: true
  mozillians_url:
    default: "https://mozillians.org"
  mozillians_app_name:
    default: "foobar"
    shadowed_by_global: true
  mozillians_app_key:
    default: "12345"
    shadowed_by_global: true
  mozillians_group_prefix:
    default: "mozillians"
